config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
    root 'notes#index'
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.where(user_id: current_user)
  end

  def show
  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end


  private

    def find_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Notenote App
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      .header_inner
        = link_to image_tag('logo.svg'), root_path, id: "logo"
        %nav
          - if user_signed_in?
            = link_to "New note", new_note_path
            = link_to "Sign Out",destroy_user_session_path, method: :delete
          - else
            = link_to "Sign Up", new_user_registration_path
            = link_to "Sign In", new_user_session_path
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

app/views/notes/edit.html.haml
.wrapper_with_padding
	%h1 Edit Note

	= render 'form'

	= link_to "Cancel", note_path

app/views/notes/index.html.haml
.wrapper_with_padding
	#notes.clearfix
		- unless @notes.blank?
			- @notes.each do |note|
				%a{ href: (url_for [note])}
					.note
						%p.title= note.title
						%p.date= time_ago_in_words(note.created_at)
		- else
			%h2 Add a Note
			%p It appears you haven't created any notes yet... Lets fix that. Why don't you go ahead and create a new note.
			%button= link_to "New Note", new_note_path

app/views/notes/new.html.haml
.wrapper_with_padding
	%h1 Add A Note

	= render 'form'

app/views/notes/show.html.haml
.wrapper_with_padding
	#note_show
		%h1.title= @note.title
		%p= simple_format(@note.content)

		.buttons
			= link_to "Back", notes_path, class: "button"
			= link_to "Edit", edit_note_path(@note), class: "button"
			= link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class: "button"

app/views/welcome/index.html.haml
#banner
	.banner_content
		%h1 NoteNote
		%p Your online notebook. Never forget an idea again.
		%button= link_to "Sign Up", new_user_registration_path

#testimonial
	.wrapper
		%p.quote "The greatest notebook application. Period."
		%p.name - Mackenzie Child

#callouts
	.callout_inner
		.wrapper
			.callout
				%h2 Remember Everything
				%p Organize your work and declutter your life. Collect everything that matters in one place and find it when you need it, fast.
			.callout
				%h2 Work Smarter
				%p Enhance your notes with links, checklists, tables, attachments, and audio recordings. Even handwritten notes are searchable.
			.callout
				%h2 Bring It All Together
				%p Organized teams get more done. From initial brainstorm to finished project, make Evernote your team hub and find productivity bliss.

#bottom_cta
	.wrapper
		%h2 Create your free account
		%p Your best ideas are always with you and always in sync.
		%button= link_to "Sign up for free", new_user_registration_path

%footer
	%p &copy; Mackenzie Child